// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjspmiljuyigrlnxhyxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqc3BtaWxqdXlpZ3JsbnhoeXhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MDY0MjMsImV4cCI6MjA2NjA4MjQyM30.Iv5P5fMc3GynbvRRl_xIrRveIbWpGiZKxakMeMfteAA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);